version: "3"
services:
  frontend:
    build: ./frontend
    ports:
      - "4200:4200"
    volumes:
      - ./frontend:/frontend
      - /src/node_modules/
    restart: always
    command: npm start
    depends_on:
      - backend
      - mongodb
  backend:
    build: ./backend/
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/backend
      - /src/node_modules/
    command: npm start
    restart: always
    depends_on:
      - mongodb
    environment:
      MONGO_DB_HOST: "mongodb://mongodb/blog"
  mongodb:
    image: mongo:4.1.7
    ports:
      - "27017:27017"
